In [1]:
import pandas as pd
import os
import pickle
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv(os.path.join("data","cars.csv"))
data

,Name,Type,AWD,RWD,Retail Price,Dealer Cost,Engine Size (l),Cyl,Horsepower(HP),City Miles Per Gallon,Highway Miles Per Gallon,Weight,Wheel Base,Len,Width
0,Acura 3.5 RL 4dr,Sedan,0,0,43755,39014,3.5,6,225,18,24,3880,115,197,72
1,Acura 3.5 RL w/Navigation 4dr,Sedan,0,0,46100,41100,3.5,6,225,18,24,3893,115,197,72
2,Acura MDX,SUV,1,0,36945,33337,3.5,6,265,17,23,4451,106,189,77
3,Acura NSX coupe 2dr manual S,Sports Car,0,1,89765,79978,3.2,6,290,17,24,3153,100,174,71
4,Acura RSX Type S 2dr,Sedan,0,0,23820,21761,2.0,4,200,24,31,2778,101,172,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,Volvo S80 2.9 4dr,Sedan,0,0,37730,35542,2.9,6,208,20,28,3576,110,190,72
383,Volvo S80 T6 4dr,Sedan,0,0,45210,42573,2.9,6,268,19,26,3653,110,190,72
384,Volvo V40,Wagon,0,0,26135,24641,1.9,4,170,22,29,2822,101,180,68
385,Volvo XC70,Wagon,1,0,35145,33112,2.5,5,208,20,27,3823,109,186,73
386,Volvo XC90 T6,SUV,1,0,41250,38851,2.9,6,268,15,20,4638,113,189,75

In [3]:
features = ['AWD','RWD','Engine Size (l)','Cyl','Horsepower(HP)','City Miles Per Gallon','Highway Miles Per Gallon','Weight','Wheel Base','Len','Width']
feature_data = data[features]
type_dummy = pd.get_dummies(data['Type']).astype(int)
feature_data = pd.concat([feature_data,type_dummy],axis=1)
feature_data

,AWD,RWD,Engine Size (l),Cyl,Horsepower(HP),City Miles Per Gallon,Highway Miles Per Gallon,Weight,Wheel Base,Len,Width,Minivan,SUV,Sedan,Sports Car,Wagon
0,0,0,3.5,6,225,18,24,3880,115,197,72,0,0,1,0,0
1,0,0,3.5,6,225,18,24,3893,115,197,72,0,0,1,0,0
2,1,0,3.5,6,265,17,23,4451,106,189,77,0,1,0,0,0
3,0,1,3.2,6,290,17,24,3153,100,174,71,0,0,0,1,0
4,0,0,2.0,4,200,24,31,2778,101,172,68,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,0,0,2.9,6,208,20,28,3576,110,190,72,0,0,1,0,0
383,0,0,2.9,6,268,19,26,3653,110,190,72,0,0,1,0,0
384,0,0,1.9,4,170,22,29,2822,101,180,68,0,0,0,0,1
385,1,0,2.5,5,208,20,27,3823,109,186,73,0,0,0,0,1
386,1,0,2.9,6,268,15,20,4638,113,189,75,0,1,0,0,0

In [4]:
X = feature_data.to_numpy()
y = data['Retail Price'].to_numpy()

In [5]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [6]:
with open('model.pkl','wb') as f:
    pickle.dump(model,f)

In [7]:
with open('model.pkl', 'rb') as f:
    model2 = pickle.load(f)

In [9]:
model2.predict(X[0,:].reshape(1,-1))

array([33002.22769507])